package com.lugo.manueln.tienda;

public interface interFragments extends principal.OnFragmentInteractionListener,infoProducto.OnFragmentInteractionListener,Buscador.OnFragmentInteractionListener,categoriasFragment.OnFragmentInteractionListener {
}
